(defpackage #:cluiless
  (:use #:alexandria #:cl)
  (:export
     #:action
     #:action-sink
     #:action-sink-map
     #:activate
     #:activate-action
     #:add-action
     #:add-action-sink
     #:application
     #:backend-error
     #:defbackend
     #:append-definitions
     #:description
     #:enabled
     #:find-action
     #:find-action-sink
     #:icon
     #:label
     #:load-backend-libraries
     #:make-action
     #:make-action-sink
     #:make-application
     #:make-window
     #:name
     #:object
     #:object-handle
     #:object-metaclass
     #:release
     #:remove-action
     #:remove-action-sink
     #:run
     #:target
     #:title
     #:valid-sites
     #:valid-site-p
     #:visible
     #:window
     #:window-by-id
     #:windows))

